### ISSUE TITLE
main.py is missing

### ISSUE THREAD

**Issue by sudo-jj** [erwald/rachel#1]
Not sure if you've got time to do an update on this project.

I tried cloning the last tree merge that had main.py, but couldn't get it working. 

> getting these errors on `python3 main.py --prepare-midi`
> Converting to input data and saving On Green Dolphin 4.mid
> Exception converting MIDI to array: 'indeterminate'
> Converting to input data and saving mendel_op19_1_format0.mid
> Exception converting MIDI to array: 'indeterminate'
> Converting to input data and saving dolphnst.mid
> Exception converting MIDI to array: 'indeterminate'

...etc

getting this error on `python main.py -t`
 

> File "main.py", line 101, in <module>
>     callbacks=[plot_train_comparison_callback, plot_test_comparison_callback])
>   File "/content/rachel/model.py", line 84, in train_model
>     validation_steps=number_of_validate_batches)
>   File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py", line 1861, in fit_generator
>     initial_epoch=initial_epoch)
>   File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py", line 1141, in fit
>     return_dict=True)
>   File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py", line 1389, in evaluate
>     tmp_logs = self.test_function(iterator)
>   File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
>     result = self._call(*args, **kwds)
>   File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py", line 895, in _call
>     filtered_flat_args, self._concrete_stateful_fn.captured_inputs)  # pylint: disable=protected-access
>   File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 1919, in _call_flat
>     ctx, args, cancellation_manager=cancellation_manager))
>   File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 560, in call
>     ctx=ctx)
>   File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
>     inputs, attrs, num_outputs)
> tensorflow.python.framework.errors_impl.InvalidArgumentError:  Specified a list with shape [4,190] from a tensor with shape [2,190]
> 	 [[node sequential/bidirectional/backward_lstm/TensorArrayUnstack/TensorListFromTensor (defined at /content/rachel/model.py:84) ]] [Op:__inference_test_function_10583]
> 
> Function call stack:
> test_function
>

**Comment by erwald** [comment]
@jha-sudo sorry, i totally missed this. the project has been stale for a while (i've been using it myself though) but i'm finishing up a major rework, which will make it much easier to use + also much better at humanizing. stay tuned!

**Comment by erwald** [comment]
@sudo-jj One year and a half later, the rewrite is now complete. Feel free to use the tool and let me know if you run into any difficulties. (There are instructions in the readme file.)
