### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by RemyThePianist** [erwald/rachel#3]
Hey! I saw your project and it intrigues me a ton! 

I would love to try it out but, I am a total noob with python and could only get past the installing pip but, I am encountering errors through trying to install the requirements. Is there a way you could add a GUI for easier use? Or create a video on FULL Install instructions because, I am having a lot of trouble. If not that is okay, I just wanted to try this humanizer out.

**Comment by erwald** [comment]
Hi @RemyThePianist , apologies for the slow reply, I only saw your message now. I have no plans to add a GUI. I may make an installation tutorial video at some point but won't give a timeline as I don't really have time/motivation for it right now. But if you can share more about where you get stuck or what error you're seeing, perhaps I could point you in the right direction?

**Comment by RemyThePianist** [comment]
I am sorry, I am new to this and I cannot for the life of me figure it out. 

I tried to install it but, from what I can understand; Installing the requirements.txt does not work due some installation errors? 

When I try to install it, it says I need to install something and when I do install what it requires, it doesn’t work. 

I would completely appreciate it if you can find time to make a tutorial to see if I am personally doing something wrong in the step process. I understand the lack of motivation. I do hope you do it.

**Comment by erwald** [comment]
No need to apologize, but I think you need to provide more detail in order for me to help you.

> When I try to install it, it says I need to install something and when I do install what it requires, it doesn’t work.

What does it output when it doesn't work? What are the precise steps you are taking before it doesn't work?

**Comment by RemyThePianist** [comment]
Thanks for the kindness.

I will try my best to give you an exact response to what is wrong when I try to install it, sometime later. I am currently away from my home (and computer) because of a major issue with the house. So, When I am back I will likely take photos and videos of the issue when trying to install. And see if that will help you help me. Thank you, Again.
