### ISSUE TITLE
Dataset used

### ISSUE THREAD

**Issue by BrothaM** [erwald/rachel#4]
Hey Erwald!

First of all - great work on this one, I personally really enjoyed messing around with it.
I was wondering what kind of dataset you've used for this one, was it a Maestro dataset?

Thank you & Cheers!

**Comment by erwald** [comment]
Hi, thanks! In the blog post, I write:

> The midihum model was trained on performances from the [International Piano-e-Competition](https://piano-e-competition.com) for pianists aged 35 and under. midihum is dedicated to those talented young performers, and those who decided on and carried out the recording and publishing of those performances.

You can find the code I used to scrape those performances here: https://github.com/erwald/midihum/blob/master/midi_scraper.py
